name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    #docker 다운로드 
    services:
      docker:
        image: docker:20.10.12
        options: --privileged
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v3
    
    # Docker 로그인 -> github에서 설정해 줘야함 따로!!
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #docker 파일 빌드하는 명령어
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nodejs-app:latest
    #container run 명령어    
    - name: Run the Docker container
      run: |
        docker run -d -p 8080:8080 --name mynodeapp nodejs-app:latest

    # Test dependencies are typically installed via a project's package.json
    # and should ideally not be handled separately in CI workflows.
    - name: Install test dependencies
      run: npm install mocha chai chai-http
    
    - name: Run tests
      run: npm test
